export const CssClasses = {
  HEADER: "header",
  NAV: "nav",
  BTN: "button",
  INPUT: "input",
  CONTROLLER: "controller",
  MAINGARAGE: "main-garage",
  GAMESPACE: "game-space",
  RACECOUNTER: "race-counter",
  PAGECOUNTER: "page-counter",
  RACEFIELD: "race-field",
  RACENAME: "race-name",
  RACEIMG: "race-img",
  FINISHIMG: "finish-img",
  CONTAINER: "container",
};
