export const CssClasses = {
  HEADER: "header",
  NAV: "nav",
  BTN: "button",
  INPUT: "input",
  CONTROLLER: "controller",
  MAINGARAGE: "main-garage",
  MAINWINNERS: "main-winners",
  GAMESPACE: "game-space",
  RACECOUNTER: "race-counter",
  PAGECOUNTER: "page-counter",
  WINNERSOUNTER: "winners-counter",
  RACEFIELD: "race-field",
  RACENAME: "race-name",
  RACEIMG: "race-img",
  FINISHIMG: "finish-img",
  CONTAINER: "container",
  NAVPAGES: "nav-pages",
  PREV: "prev",
  NEXT: "next",
  MODALWINDOW: "modal-window",
  WINNERSTABLE: "winners-table",
  WINNERSSTRING: "winners-string",
};
